apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "shuja-nodejs-postgres"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shujaahmedi2l/shuja-nodejs-postgres.git
    targetRevision: master
    path: helm/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: "shuja-nodejs-postgres"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
